Repository googleapis/python-api-core, pull requests merged in 2020-12, with the labels that each got.

#102 chore: update code of conduct, intersphinx links (via synth)
  .kokoro/docs/common.cfg
  CODE_OF_CONDUCT.md
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: full

#103 chore: add config / docs for 'pre-commit' support
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full

#105 chore: add 'docfx' nox session
  noxfile.py
Labels: cla: yes

#111 feat: add support for Python 3.9
  noxfile.py
  setup.py
Labels: cla: yes

#114 chore: tweak 'python_requires' to match supported Python versions
  noxfile.py
  setup.py
Labels: cla: yes

#109 docs: explain how to create credentials from dict
  docs/auth.rst
Labels: automerge, cla: yes

#115 fix: support 'retry' for operations built from HTTP/gRPC responses
  google/api_core/operation.py
  tests/unit/test_operation.py
Labels: cla: yes

#119 chore(deps): update precommit hook pre-commit/pre-commit-hooks to v3.4.0
  .pre-commit-config.yaml
  synth.metadata
Labels: cla: yes, context: partial

#120 docs(python): document adding Python 3.9 support, dropping 3.5 support
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full
