Repository googleapis/python-api-core, pull requests merged in 2020-06, with the labels that each got.

#28 feat: AsyncIO Integration [Part 2]
  docs/futures.rst
  docs/operation.rst
  docs/page_iterator.rst
  google/api_core/future/async_future.py
  google/api_core/operation_async.py
  google/api_core/page_iterator_async.py
  tests/asyncio/future/__init__.py
  tests/asyncio/future/test_async_future.py
  tests/asyncio/test_operation_async.py
  tests/asyncio/test_page_iterator_async.py
Labels: automerge, cla: yes

#29 feat: AsyncIO Integration [Part 3]
  google/api_core/gapic_v1/__init__.py
  google/api_core/gapic_v1/method_async.py
  google/api_core/grpc_helpers.py
  google/api_core/grpc_helpers_async.py
  google/api_core/operations_v1/__init__.py
  google/api_core/operations_v1/operations_async_client.py
  tests/asyncio/gapic/test_method_async.py
  tests/asyncio/operations_v1/__init__.py
  tests/asyncio/operations_v1/test_operations_async_client.py
  tests/asyncio/test_grpc_helpers_async.py
Labels: cla: yes

#36 feat(client_options): add new options 'quota_project' and 'credentialsAdd 'credentials_file' and 'quota_project' client options
  google/api_core/client_options.py
  tests/unit/test_client_options.py
Labels: cla: yes

#41 fix: Bump up grpcio minimum version
  setup.py
Labels: cla: yes

#44 chore: update templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  CONTRIBUTING.rst
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  testing/.gitignore
Labels: cla: yes

#30 feat: allow disabling response stream pre-fetch
  google/api_core/grpc_helpers.py
  tests/unit/test_grpc_helpers.py
Labels: automerge, cla: yes

#49 fix(dependencies): increase protobuf version
  setup.py
Labels: cla: yes

#50 feat: allow credentials files to be passed for channel creation
  .gitignore
  google/api_core/exceptions.py
  google/api_core/grpc_helpers.py
  google/api_core/grpc_helpers_async.py
  setup.py
  tests/asyncio/test_grpc_helpers_async.py
  tests/unit/test_grpc_helpers.py
Labels: cla: yes

#56 chore: update docs/conf.py
  .gitignore
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: partial

#53 docs: change the documentation for using 'six.moves.collections_abc.Mapping' instead of 'dict' in 'client_options.from_dict()'
  google/api_core/client_options.py
Labels: cla: yes

#59 chore: update Py2 support msg to reflect passage of time
  docs/_templates/layout.html
  synth.metadata
Labels: cla: yes, context: full
