Repository googleapis/python-api-core, pull requests merged in 2020-10, with the labels that each got.

#78 fix(deps): require six >= 1.13.0
  setup.py
Labels: cla: yes

#88 fix: harden install to use full paths, and windows separators on windows
  setup.py
Labels: cla: yes

#90 chore: preserve 'pytype' artifacts during synth
  .github/snippet-bot.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/populate-secrets.sh
  .kokoro/publish-docs.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CONTRIBUTING.rst
  docs/conf.py
  scripts/decrypt-secrets.sh
  setup.cfg
  synth.metadata
  synth.py
Labels: cla: yes

#86 fix: map LRO errors to library exception types
  google/api_core/exceptions.py
  google/api_core/operation.py
  tests/unit/test_exceptions.py
  tests/unit/test_operation.py
Labels: cla: yes

#92 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#93 style: update out-of-date comment in exceptions.py
  google/api_core/exceptions.py
Labels: cla: yes

#95 chore: add actools-python to CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#9 feat(api-core): pass retry from result() to done()
  google/api_core/future/polling.py
  tests/unit/future/test_polling.py
Labels: automerge, cla: yes, type: feature request

#98 chore: add a sync-repo-settings file
  .github/sync-repo-settings.yaml
Labels: cla: yes
