Repository googleapis/python-api-core, pull requests merged in 2021-03, with the labels that each got.

#155 fix: save empty IAM policy bindings
  google/api_core/iam.py
  tests/unit/test_iam.py
Labels: cla: yes

#147 docs: update python contributing guide
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full

#159 fix: skip empty policy bindings in `len()` and `iter()`
  google/api_core/iam.py
  tests/unit/test_iam.py
Labels: automerge, cla: yes

#164 Fix retry.with_delay multiplier parameter handling
  google/api_core/retry.py
  tests/unit/test_retry.py
Labels: automerge, cla: yes
