Repository googleapis/python-api-core, pull requests merged in 2021-08, with the labels that each got.

#228 fix: strip trailing `_` from field mask paths
  google/api_core/protobuf_helpers.py
  noxfile.py
  tests/unit/test_protobuf_helpers.py
Labels: cla: yes

#212 fix!: drop support for Python 2.7 / 3.5
  CONTRIBUTING.rst
  README.rst
  docs/auth.rst
  google/api_core/bidi.py
  google/api_core/client_info.py
  google/api_core/client_options.py
  google/api_core/datetime_helpers.py
  google/api_core/exceptions.py
  google/api_core/future/base.py
  google/api_core/gapic_v1/__init__.py
  google/api_core/gapic_v1/client_info.py
  google/api_core/gapic_v1/config.py
  google/api_core/gapic_v1/method.py
  google/api_core/gapic_v1/method_async.py
  google/api_core/gapic_v1/routing_header.py
  google/api_core/general_helpers.py
  google/api_core/grpc_helpers.py
  google/api_core/iam.py
  google/api_core/operations_v1/__init__.py
  google/api_core/page_iterator.py
  google/api_core/path_template.py
  google/api_core/protobuf_helpers.py
  google/api_core/retry.py
  google/api_core/timeout.py
  google/api_core/version.py
  noxfile.py
  owlbot.py
  setup.py
  testing/constraints-2.7.txt
  testing/constraints-3.6.txt
  tests/unit/test_bidi.py
  tests/unit/test_datetime_helpers.py
  tests/unit/test_exceptions.py
  tests/unit/test_general_helpers.py
  tests/unit/test_page_iterator.py
Labels: cla: yes, semver: major

#241 chore: remove non-custom rules from sync-repo-settings
  .github/sync-repo-settings.yaml
Labels: cla: yes

#246 chore: avoid duplicating pins of grpcio in noxfile
  noxfile.py
Labels: cla: yes

#251 fix: strip trailing _ from field mask paths
  google/api_core/protobuf_helpers.py
  noxfile.py
  tests/unit/test_protobuf_helpers.py
Labels: cla: yes

#253 chore: update if_transient_error docs to match behaviour
  google/api_core/retry.py
Labels: cla: yes, automerge

#234 fix: bump grpcio version to use stable aio API
  google/api_core/grpc_helpers_async.py
  setup.py
  testing/constraints-3.6.txt
  tests/asyncio/gapic/test_method_async.py
  tests/asyncio/operations_v1/test_operations_async_client.py
  tests/asyncio/test_grpc_helpers_async.py
Labels: cla: yes

#256 chore: release 1.31.2
  CHANGELOG.md
  google/api_core/version.py
Labels: cla: yes

#247 tests: silence a warning from 'charset_normalizer'
  google/api_core/retry.py
  tests/unit/test_exceptions.py
Labels: cla: yes

#264 chore: migrate default branch to main
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  google/api_core/exceptions.py
  google/api_core/future/async_future.py
  google/api_core/future/polling.py
  noxfile.py
  owlbot.py
Labels: cla: yes

#261 tests: close coverage gap for race condition
  tests/unit/test_bidi.py
Labels: cla: yes

#258 fix: do not error on LROs with no response or error
  google/api_core/operation.py
  google/api_core/operation_async.py
  tests/asyncio/test_operation_async.py
  tests/unit/test_operation.py
Labels: cla: yes
