Repository googleapis/python-api-core, pull requests merged in 2021-01, with the labels that each got.

#125 chore: use 'http' in URL for Apache license
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: cla: yes, context: full

#122 chore: add constraints file
  noxfile.py
  setup.py
  testing/constraints-2.7.txt
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: automerge, cla: yes

#127 feat: allow gRPC metadata to be passed to operations client
  google/api_core/operation.py
  google/api_core/operation_async.py
  google/api_core/operations_v1/operations_async_client.py
  google/api_core/operations_v1/operations_client.py
  tests/asyncio/operations_v1/test_operations_async_client.py
  tests/asyncio/test_operation_async.py
  tests/unit/operations_v1/test_operations_client.py
  tests/unit/test_operation.py
Labels: cla: yes

#129 chore: tweak kokoro config (via synth)
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  synth.metadata
Labels: cla: yes, context: full

#131 docs: fix spelling errors in retry
  google/api_core/retry.py
Labels: automerge, cla: yes

#135 build(python): make `NOX_SESSION` optional
  .trampolinerc
  synth.metadata
Labels: cla: yes, context: full

#133 fix: add operation name to x-goog-request-params
  google/api_core/operations_v1/operations_client.py
  tests/unit/operations_v1/test_operations_client.py
Labels: cla: yes, kokoro:force-run

#138 chore: Add header checker config to python library synth
  .github/header-checker-lint.yml
  synth.metadata
Labels: cla: yes, context: full

#139 feat: require python >= 3.6
  README.rst
  google/__init__.py
  google/api_core/future/polling.py
  google/api_core/gapic_v1/__init__.py
  google/api_core/gapic_v1/routing_header.py
  google/api_core/iam.py
  google/api_core/operations_v1/__init__.py
  google/api_core/protobuf_helpers.py
  google/api_core/version.py
  noxfile.py
  setup.py
Labels: cla: yes

#140 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: cla: yes
