Repository googleapis/python-api-core, pull requests merged in 2021-04, with the labels that each got.

#167 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: cla: yes, context: full, samples

#172 chore: prevent normalization of semver versioning
  setup.py
Labels: cla: yes

#173 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  synth.metadata
Labels: automerge, cla: yes

#174 chore(revert): revert preventing normalization
  setup.py
Labels: cla: yes
