Repository googleapis/python-api-core, pull requests merged in 2022-11, with the labels that each got.

#462 fix: Major refactoring of Polling, Retry and Timeout logic
  .github/workflows/lint.yml
  .github/workflows/mypy.yml
  google/api_core/extended_operation.py
  google/api_core/future/async_future.py
  google/api_core/future/polling.py
  google/api_core/gapic_v1/config.py
  google/api_core/gapic_v1/method.py
  google/api_core/grpc_helpers.py
  google/api_core/operation.py
  google/api_core/operations_v1/operations_async_client.py
  google/api_core/operations_v1/operations_client.py
  google/api_core/operations_v1/operations_client_config.py
  google/api_core/operations_v1/transports/rest.py
  google/api_core/retry.py
  google/api_core/retry_async.py
  google/api_core/timeout.py
  noxfile.py
  tests/asyncio/gapic/test_method_async.py
  tests/asyncio/operations_v1/test_operations_async_client.py
  tests/asyncio/test_grpc_helpers_async.py
  tests/asyncio/test_operation_async.py
  tests/asyncio/test_retry_async.py
  tests/unit/future/test_polling.py
  tests/unit/gapic/test_method.py
  tests/unit/operations_v1/test_operations_client.py
  tests/unit/operations_v1/test_operations_rest_client.py
  tests/unit/test_bidi.py
  tests/unit/test_client_info.py
  tests/unit/test_exceptions.py
  tests/unit/test_general_helpers.py
  tests/unit/test_grpc_helpers.py
  tests/unit/test_operation.py
  tests/unit/test_retry.py
  tests/unit/test_timeout.py
Labels: size: xl

#463 fix: require google-auth >= 2.14.1
  setup.py
  testing/constraints-3.7.txt
Labels: size: xs

#466 feat: add support for Python 3.11
  .github/sync-repo-settings.yaml
  .github/workflows/unittest.yml
  CONTRIBUTING.rst
  noxfile.py
  setup.py
Labels: size: s

#465 feat: Allow representing enums with their unqualified symbolic names in headers
  google/api_core/gapic_v1/routing_header.py
  noxfile.py
  owlbot.py
  tests/unit/gapic/test_routing_header.py
Labels: size: m
