Repository googleapis/python-api-core, pull requests merged in 2022-06, with the labels that each got.

#395 docs: Fix typo in the BackgroundConsumer docstring
  google/api_core/bidi.py
Labels: automerge, size: xs

#397 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: size: s

#401 fix: drop support for grpcio-gcp
  .github/sync-repo-settings.yaml
  .github/workflows/unittest.yml
  google/api_core/grpc_helpers.py
  google/api_core/grpc_helpers_async.py
  noxfile.py
  setup.py
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  tests/asyncio/test_grpc_helpers_async.py
  tests/unit/test_grpc_helpers.py
Labels: size: m

#400 fix(deps): allow protobuf < 5.0.0
  setup.py
Labels: size: xs
