Repository googleapis/python-api-core, pull requests merged in 2023-11, with the labels that each got.

#541 fix: drop usage of distutils
  google/api_core/operations_v1/abstract_operations_client.py
Labels: size: s

#543 fix: add warning to retry target to avoid incorrect usage
  google/api_core/retry.py
  tests/unit/test_retry.py
Labels: size: s

#544 fix: update OperationsAsyncClient to use AsyncRetry
  google/api_core/operations_v1/operations_async_client.py
Labels: size: xs

#550 feat: support with_call for wrapped rpcs
  google/api_core/gapic_v1/method.py
  tests/unit/gapic/test_method.py
Labels: size: s

#552 fix: replace deprecated `datetime.datetime.utcnow()`
  google/api_core/datetime_helpers.py
  noxfile.py
  testing/constraints-3.12.txt
  tests/asyncio/test_retry_async.py
  tests/unit/test_retry.py
  tests/unit/test_timeout.py
Labels: size: s

#554 feat: add type annotations to wrapped grpc calls
  google/api_core/grpc_helpers.py
  google/api_core/grpc_helpers_async.py
  tests/asyncio/test_grpc_helpers_async.py
  tests/unit/test_grpc_helpers.py
Labels: size: m

#546 feat: add universe_domain attribute to ClientOptions
  google/api_core/client_options.py
  tests/unit/test_client_options.py
Labels: size: s
