Repository googleapis/python-api-core, pull requests merged in 2023-12, with the labels that each got.

#562 fix: fix regression in `bidi` causing `Thread-ConsumeBidirectionalStream caught unexpected exception and will exit`
  google/api_core/bidi.py
Labels: size: xs

#561 feat: Introduce compatibility with native namespace packages
  google/__init__.py
  setup.py
  tests/unit/test_packaging.py
Labels: size: m

#563 chore: simplify bidi.py:_RequestQueueGenerator._is_active()
  google/api_core/bidi.py
Labels: automerge, size: xs

#564 build: treat warnings as errors
  pytest.ini
  tests/unit/test_iam.py
Labels: size: s

#495 feat: retry and retry_async support streaming rpcs
  google/api_core/__init__.py
  google/api_core/retry.py
  google/api_core/retry/__init__.py
  google/api_core/retry/retry_base.py
  google/api_core/retry/retry_streaming.py
  google/api_core/retry/retry_streaming_async.py
  google/api_core/retry/retry_unary.py
  google/api_core/retry/retry_unary_async.py
  google/api_core/retry_async.py
  tests/asyncio/retry/__init__.py
  tests/asyncio/retry/test_retry_streaming_async.py
  tests/asyncio/retry/test_retry_unary_async.py
  tests/unit/retry/__init__.py
  tests/unit/retry/test_retry_base.py
  tests/unit/retry/test_retry_streaming.py
  tests/unit/retry/test_retry_unary.py
Labels: kokoro:force-run, size: xl
