Repository googleapis/python-api-core, pull requests merged in 2024-02, with the labels that each got.

#596 docs: fix typo in the docstring of `AsyncStreamingRetry`
  google/api_core/retry/retry_streaming_async.py
  google/api_core/retry/retry_unary_async.py
Labels: size: xs

#583 feat: Add attempt_direct_path argument to create_channel
  google/api_core/grpc_helpers.py
  google/api_core/grpc_helpers_async.py
  pytest.ini
  tests/asyncio/test_grpc_helpers_async.py
  tests/unit/test_grpc_helpers.py
Labels: size: l

#595 chore: Delete tests/unit/test_general_helpers.py
  tests/unit/test_general_helpers.py
Labels: size: s

#604 fix: resolve issue handling protobuf responses in rest streaming
  google/api_core/rest_streaming.py
  tests/unit/test_rest_streaming.py
Labels: size: l

#607 chore: try cherry-pick-bot
  .github/cherry-pick-bot.yml
Labels: size: xs

#610 ci(v1): fix builds in v1 branch
  noxfile.py
Labels: size: s

#614 fix: Add _registered_method to grpc ChannelStub
  google/api_core/grpc_helpers.py
Labels: size: s

#626 fix(deps): Require proto-plus >= 1.22.3
  noxfile.py
  setup.py
  testing/constraints-3.7.txt
  tests/unit/test_protobuf_helpers.py
Labels: size: s
