Repository googleapis/python-api-core, pull requests merged in 2024-10, with the labels that each got.

#713 fix: Switch to unittest.mock from mock
  noxfile.py
  tests/asyncio/future/test_async_future.py
  tests/asyncio/gapic/test_method_async.py
  tests/asyncio/operations_v1/test_operations_async_client.py
  tests/asyncio/retry/test_retry_streaming_async.py
  tests/asyncio/retry/test_retry_unary_async.py
  tests/asyncio/test_grpc_helpers_async.py
  tests/asyncio/test_operation_async.py
  tests/asyncio/test_page_iterator_async.py
  tests/asyncio/test_rest_streaming_async.py
  tests/unit/future/test__helpers.py
  tests/unit/future/test_polling.py
  tests/unit/gapic/test_method.py
  tests/unit/operations_v1/test_operations_rest_client.py
  tests/unit/retry/test_retry_base.py
  tests/unit/retry/test_retry_streaming.py
  tests/unit/retry/test_retry_unary.py
  tests/unit/test_bidi.py
  tests/unit/test_exceptions.py
  tests/unit/test_extended_operation.py
  tests/unit/test_grpc_helpers.py
  tests/unit/test_operation.py
  tests/unit/test_page_iterator.py
  tests/unit/test_path_template.py
  tests/unit/test_timeout.py
Labels: size: m

#696 feat: add support for python 3.13
  .github/workflows/unittest.yml
  CONTRIBUTING.rst
  noxfile.py
  setup.py
  testing/constraints-3.13.txt
  tests/asyncio/retry/test_retry_streaming_async.py
  tests/asyncio/test_page_iterator_async.py
Labels: size: s

#735 fix: add type hints to ClientOptions
  google/api_core/client_options.py
Labels: size: s

#668 chore: move retry async check to wrap time
  google/api_core/retry/retry_unary.py
  tests/unit/retry/test_retry_unary.py
Labels: size: s

#666 feat: add caching to GapicCallable
  google/api_core/gapic_v1/method.py
  tests/unit/gapic/test_method.py
Labels: size: m

#738 chore: update templated files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/requirements.txt
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/requirements.txt
Labels: size: l, process: review requested

#743 chore: Revert "chore: move retry async check to wrap time"
  google/api_core/retry/retry_unary.py
  tests/unit/retry/test_retry_unary.py
Labels: size: s

#740 fix: require proto-plus >= 1.25.0 for Python 3.13
  setup.py
Labels: size: xs

#744 chore: Revert "feat: add caching to GapicCallable"
  google/api_core/gapic_v1/method.py
  tests/unit/gapic/test_method.py
Labels: size: m

#746 chore: update templated files
  .github/.OwlBot.lock.yaml
  .kokoro/docs/common.cfg
  .kokoro/release/common.cfg
  .kokoro/samples/python3.13/common.cfg
  .kokoro/samples/python3.13/continuous.cfg
  .kokoro/samples/python3.13/periodic-head.cfg
  .kokoro/samples/python3.13/periodic.cfg
  .kokoro/samples/python3.13/presubmit.cfg
Labels: size: m

#736 feat: migrate to pyproject.toml
  mypy.ini
  pyproject.toml
  pytest.ini
  setup.py
Labels: size: m
