Repository googleapis/python-api-core, pull requests merged in 2024-06, with the labels that each got.

#653 chore: fallback to unary_unary when wrapping async callables
  google/api_core/grpc_helpers_async.py
  tests/asyncio/test_grpc_helpers_async.py
Labels: size: s

#651 fix: Ignore unknown fields in rest streaming.
  google/api_core/rest_streaming.py
Labels: size: xs

#649 chore: move retry async check to wrap time
  google/api_core/retry/retry_unary.py
  tests/unit/retry/test_retry_unary.py
Labels: size: s

#665 chore(revert): Revert "feat: add caching to GapicCallable"
  google/api_core/gapic_v1/method.py
  tests/unit/gapic/test_method.py
Labels: size: m

#667 chore(revert): Revert "chore: move retry async check to wrap time (#649)"
  google/api_core/retry/retry_unary.py
  tests/unit/retry/test_retry_unary.py
Labels: size: s

#644 fix: add support for protobuf 5.x
  .github/workflows/unittest.yml
  google/api_core/operations_v1/__init__.py
  google/api_core/operations_v1/transports/base.py
  google/api_core/operations_v1/transports/rest.py
  noxfile.py
  owlbot.py
  pytest.ini
  setup.py
  tests/unit/test_rest_streaming.py
Labels: size: m
