Repository googleapis/python-api-core, pull requests merged in 2025-03, with the labels that each got.

#801 build: fix mypy issues
  google/api_core/retry/retry_streaming.py
  google/api_core/retry/retry_streaming_async.py
  noxfile.py
Labels: size: s

#804 fix(deps): allow protobuf 6.x
  pyproject.toml
Labels: size: s

#803 build: remove unused docs scripts
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
Labels: size: l

#793 feat: support dynamic retry backoff values
  google/api_core/retry/retry_base.py
  google/api_core/retry/retry_streaming.py
  google/api_core/retry/retry_streaming_async.py
  google/api_core/retry/retry_unary.py
  google/api_core/retry/retry_unary_async.py
  tests/asyncio/retry/test_retry_streaming_async.py
  tests/asyncio/retry/test_retry_unary_async.py
  tests/unit/retry/test_retry_streaming.py
  tests/unit/retry/test_retry_unary.py
Labels: size: m
